Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/03/2021
Var
// Seção de Declarações das variáveis 
a,b,c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a <- 15
b <- 30

escreva("o valor de a é: ",a)
escreva("o valor de b é: ",b)


c <- a
a <- b
b <- c

escreva("o valor de a é: ",a)
escreva("o valor de b é: ",b)

Fimalgoritmo